 PREFIX resplan: <http://resplan.org/resplan#>

 CONSTRUCT {
    ?newDoor a resplan:Door ;
            resplan:sourceId ?newId ;
            resplan:connectsSpace ?a, ?b .
 }
 WHERE {
    ?a resplan:connectedViaDoor ?b .
    FILTER (?a != ?b)
    FILTER (STR(?a) < STR(?b))  # To avoid duplicate doors between same spaces
    FILTER NOT EXISTS {
        ?door a resplan:Door ;
                resplan:connectsSpace ?a, ?b .  
    }
    BIND(IRI(CONCAT("http://resplan.org/resplan/infer#", STRUUID())) AS ?newDoor)
    BIND(CONCAT("DO-INF-", STRUUID()) AS ?newId )
 }